market/market/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from market import settings
from django.conf.urls.static import static
from basket import views

urlpatterns = [
    path('reviews/', include('reviews.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('basket.urls')),   
    path('', include('product.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('apiload.urls')),
    
    # re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    

]

if settings.DEBUG:
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls"))
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/users/urls.py
from django.urls import path, include, re_path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    
    path('login', LoginUser.as_view(), name="login"),
    path('register', RegisterUser.as_view(), name="register"),
    path('logout', logout_user, name="logout"),
    path('lk', profile_update, name="lk"),
    # re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    
     path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

market/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from .services import *


class CustomUser(AbstractUser):
    photo = models.ImageField(upload_to="photo_user/%Y/%m/%d", null=True, verbose_name='photo', blank=True)
    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")
    phone_number = models.CharField(validators=[phoneNumberRegex], max_length=16, null=True, unique=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.photo:
            self.photo = make_thumbnail(self.photo, self.username)
            super().save(*args, **kwargs)
   

market/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    # password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1']

    
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        del self.fields['password2']


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-profile-data'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-profile-data'}), required=False)
    first_name = forms.CharField(label='Firstname', widget=forms.TextInput(attrs={'class': 'form-profile-data'}), required=False)
    phone_number = forms.CharField(label='Phone', widget=forms.TextInput(attrs={'class': 'form-profile-data'}), required=False)
    photo = forms.ImageField(widget=forms.FileInput, required=False)
    
    
    # def clean_avatar(self):
    #     avatar = self.cleaned_data.get('avatar')
    #     if avatar is None:
    #         raise forms.ValidationError(u'Добавьте картинку')
    #     if 'image' not in avatar.content_type:
    #         raise forms.ValidationError(u'Неверный формат картинки')
    #     return avatar
    
    
    class Meta:
        model = CustomUser
        fields = ['photo', 'username', 'first_name','email',  'phone_number']


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

market/users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout, login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import CustomUserCreationForm, LoginUserForm, UpdateUserForm
from .models import CustomUser

class RegisterUser(CreateView):
    form_class = CustomUserCreationForm
    # success_url = reverse_lazy('login')
    template_name = 'users/register.html'
    #
    # def post(self, request, *args, **kwargs):
    #     form = CustomUserCreationForm(request.POST)
    #     if form.is_valid():
    #         user = form.save(commit=False)
    #         user.save()

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


def logout_user(request):
    logout(request)
    return redirect('login')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'



@login_required
def profile_update(request):
    if request.method == 'POST':
        user = CustomUser.objects.get(username=request.user)
        user_form = UpdateUserForm(request.POST, request.FILES, instance=user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Your profile is updated successfully')
            # print(user_form.username)
            return redirect('lk')

    else:
        user_form = UpdateUserForm(instance=request.user)

    context = {
        'user_form': user_form,
    }

    return render(request, 'users/personal-page.html', context)


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password-reset.html'
    email_template_name = 'users/password-reset-email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('home')

market/users/templates/users/login.html
{% extends 'product/base.html' %}


{% block content %}

<div class="form-page">    

<div class="form">    
    <h1 class="form-title"> Log in</h1>
    <!-- <div class="form"> -->
        <form method="POST">
            {% csrf_token %}
            {% for f in form %}
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
            <a href="{% url 'password_reset' %}"><i>Forgot Password?</i></a>
            {% comment %} <a href="{% url 'social:begin' 'github' %}" class="github-login">Sign in with GitHub</a> {% endcomment %}
            <button class="form-button" type="submit">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}

market/users/templates/users/password-reset-email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}

market/users/templates/users/password-reset.html
{% extends 'product/base.html' %}


{% block content %}



<div class="card-body">
        <form method="POST">
            {% csrf_token %}
                <div class="form-group">
                    <label class="small mb-1" for="id_email">Email</label>
                    <input type="email" name="email"  class="form-control"
                            autocomplete="email" maxlength="254" required id="id_email"
                            placeholder="Enter email">
                </div>
                    <button type="submit" class="col-md-12 btn btn-dark">Submit
                    </button>
        </form>
    </div>
    <div class="card-footer text-center">
        <div class="small">
            <a href="{% url 'register' %}">Create A New Account</a><br><br>
            <a href="{% url 'login' %}">Back To Login</a><br>
        </div>
    </div>
</div>

{% endblock %}

market/users/templates/users/password_reset_confirm.html
{% extends 'product/base.html' %}


{% block content %}

<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                {% if validlink %}
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password1">New Password</label>
                                            <input type="password" name="new_password1" autocomplete="new-password"
                                                   class="form-control" required id="id_new_password1"
                                                   placeholder="Enter password"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                            <input type="password" name="new_password2" autocomplete="new-password"
                                                   required id="id_new_password2" class="form-control"
                                                   placeholder="Confirm password"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                {% else %}
                <div class="alert alert-warning">
                    The password reset link was invalid, possibly because it has already been used.
                    Please request a new password reset.
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

market/users/templates/users/personal-page.html
{% extends 'product/base.html' %}
{% load static %}


{% block content %}
<link type="text/css" href="{% static 'users/css/profile.css' %}" rel="stylesheet" />

<header class="header__personal-page">
    <h2 class="profile"> Profile</h1>
</header>

<div class="body-profile">
    {% if messages %}
    <ul class="messages" id="messages">
        {% for message in messages %}
        <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %} id="message"> {{ message }} </li>
        {% endfor %}
    </ul>
    <script>
        var message_ele = document.getElementById("messages");
        setTimeout(function(){ 
        message_ele.style.display = "none"; 
        }, 3000);
    </script>
    {% endif %}

    <div class="form-profile">   
        <form class="user-personal-page" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-profile__container">
                    {% for f in user_form %}
                    
                    {% if forloop.first %}
                    <div class="profile-img">
                        {% if user.photo %}
                            <img class="profimg" src="{{ user.photo.url }} " alt="HUI">

                            
                        {% else %}
                            <img class="defoult-profile-images" src="{% static 'users/images/defoult-profile.jpg' %}" alt="HUI">
                        {% endif %}
                    </div>
                    <div class="image-field">
                        <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                        {{ f }}
                    </div>

                    {% else %}

                    <div class="form-data">
                        <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                        {{ f }}
                    </div>
                    <div class="form-error">{{ f.errors }}</div>
                    {% endif %}

                    {% endfor %}
                    <div class="buttons-form">
                        <button type="reset" class="form-button__reset">Reset</button>
                        <button class="form-button__change-profile" type="submit">Save</button> 
                    </div>
            </div>
                
                
                </div>
            </form>
    </div>  


    <div class="right-bar-profile">

        
    </div>
            
</div>

<footer class="page-down">


</footer>

{% endblock %}

market/users/templates/users/register.html
{% extends 'product/base.html' %}


{% block content %}

<div class="form-page">    

<div class="form">    
    <h1 class="form-title"> Sign Up</h1>
    <!-- <div class="form"> -->
        <form method="POST">
            {% csrf_token %}
            {% for f in form %}
            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
            {{ f }}
            <div class="form-error">{{ f.errors }}</div>
            {% endfor %}
            <button class="form-button" type="submit">Sign up</button>
        </form>
    </div>
</div>
{% endblock %}